# Generated by Django 3.2.7 on 2021-11-10 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adubo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=240, verbose_name='Nome')),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário Registrado')),
            ],
            options={
                'verbose_name': 'Adubo',
                'verbose_name_plural': 'Adubos',
            },
        ),
        migrations.CreateModel(
            name='ArquivoDigitalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=340, verbose_name='Descricao')),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário registrado')),
            ],
            options={
                'verbose_name': 'Anotação da Consultoria',
                'verbose_name_plural': 'Anotações da Consultoria',
            },
        ),
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=240, verbose_name='Nome')),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário Registrado')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_proprietario_Fazenda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fazenda',
                'verbose_name_plural': 'Fazendas',
            },
        ),
        migrations.CreateModel(
            name='Maquinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Trator'), (2, 'Emplemento')], verbose_name='Tipo de Maquinário')),
                ('marca', models.CharField(max_length=200, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=200, verbose_name='Modelo')),
                ('ano_fabricacao', models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário Registrado')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_fazenda_Maquinario', to='manager.fazenda')),
            ],
            options={
                'verbose_name': 'Maquinário',
                'verbose_name_plural': 'Maquinários',
            },
        ),
        migrations.CreateModel(
            name='Variedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=240, unique=True, verbose_name='Nome')),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário Registrado')),
            ],
            options={
                'verbose_name': 'Variedade',
                'verbose_name_plural': 'Variedades',
            },
        ),
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('ano_plantio', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ano do plantio')),
                ('numero_covas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero de covas')),
                ('espacamento_rua', models.FloatField(blank=True, null=True, verbose_name='Espaçamento das ruas')),
                ('espacamento_cova', models.FloatField(blank=True, null=True, verbose_name='Espaçamento das covas')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='Área em hectare')),
                ('numero_covas_hectare', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de covas por hectare')),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário Registrado')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_fazenda_Talhao', to='manager.fazenda')),
                ('variedade', models.ManyToManyField(related_name='id_variedade_Talhao', to='manager.Variedade')),
            ],
            options={
                'verbose_name': 'Talhao',
                'verbose_name_plural': 'Talhôes',
            },
        ),
        migrations.CreateModel(
            name='PrestacaoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Plantio'), (2, 'Fertilização'), (3, 'Preparação do Solo'), (4, 'Outros')], verbose_name='Tipo de Serviço')),
                ('data_inicio', models.DateField(verbose_name='Data de Inicio')),
                ('data_termino', models.DateField(verbose_name='Data de Término')),
                ('status', models.CharField(choices=[('A', 'Andamento'), ('C', 'Concluído')], max_length=2, verbose_name='Status')),
                ('observacoes', models.TextField(verbose_name='Observações')),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário Registrado')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_funcionario_ServicoMaquinario', to=settings.AUTH_USER_MODEL)),
                ('maquinario', models.ManyToManyField(related_name='id_maquinario_ServicoMaquinario', to='manager.Maquinario')),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_talhao_ServicoMaquinario', to='manager.talhao')),
            ],
            options={
                'verbose_name': 'Prestação de Serviço',
                'verbose_name_plural': 'Prestação dos Serviços',
            },
        ),
        migrations.CreateModel(
            name='Plantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário Registrado')),
                ('prestacao_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_servico_Plantio', to='manager.prestacaoservico')),
            ],
            options={
                'verbose_name': 'Plantio',
                'verbose_name_plural': 'Plantios',
            },
        ),
        migrations.CreateModel(
            name='FuncionarioFazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('A', 'Agrônomo'), ('F', 'Funcionário')], max_length=1)),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário Registrado')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_fazenda_FuncionarioFazenda', to='manager.fazenda')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_funcionario_FuncionarioFazenda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcionario da Fazenda',
                'verbose_name_plural': 'Funcionarios da Fazenda',
            },
        ),
        migrations.CreateModel(
            name='Fertilizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Inicio')),
                ('data_termino', models.DateField(verbose_name='Data de Término')),
                ('observacoes', models.TextField(verbose_name='Observações')),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário Registrado')),
                ('adubo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_adubo_Fertilizacao', to='manager.adubo')),
                ('prestacao_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_servico_Fertilizacao', to='manager.prestacaoservico')),
            ],
            options={
                'verbose_name': 'Fertilização',
                'verbose_name_plural': 'Fertilizaçôes',
            },
        ),
        migrations.CreateModel(
            name='ConsultoriaAgronomo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário Registrado')),
                ('agronomo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_agronomo_ConsultoriaAgronomo', to=settings.AUTH_USER_MODEL)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_fazenda_ConsultoriaAgronomo', to='manager.fazenda')),
            ],
            options={
                'verbose_name': 'Consultoria do Agrônomo',
                'verbose_name_plural': 'Consultorias do Agrônomo',
            },
        ),
        migrations.CreateModel(
            name='Colheita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo', models.IntegerField(choices=[('MQ', 'Máquina'), ('MA', 'Mão')], verbose_name='Tipo de Serviço')),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário Registrado')),
                ('prestacao_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_servico_Colheita', to='manager.prestacaoservico')),
            ],
            options={
                'verbose_name': 'Colheita',
                'verbose_name_plural': 'Colheitas',
            },
        ),
        migrations.CreateModel(
            name='AnotacaoConsultoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.CharField(max_length=340, verbose_name='Descricao')),
                ('litros_cova', models.FloatField(verbose_name='Litros por cova')),
                ('produtividade', models.FloatField(verbose_name='Produtividade por pé')),
                ('produtividade_sacas_hectare', models.FloatField(verbose_name='Produtividade em sacas por hectare')),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário registrado')),
                ('consultoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_consultoria_AnotacaoConsultoria', to='manager.consultoriaagronomo')),
                ('variedade', models.ManyToManyField(related_name='id_variedade_AnotacaoConsultoria', to='manager.Variedade')),
            ],
            options={
                'verbose_name': 'Anotação da Consultoria',
                'verbose_name_plural': 'Anotações da Consultoria',
            },
        ),
    ]
