# Generated by Django 3.2.7 on 2021-10-04 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=194, unique=True, verbose_name='E-mail')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=150, verbose_name='Sobrenome')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(null=True, verbose_name='Data de nascimento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Usuário ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Usuário desenvolvedor')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super usuário')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=240, verbose_name='Nome')),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário Registrado')),
                ('agronomos', models.ManyToManyField(related_name='agronomos', to=settings.AUTH_USER_MODEL)),
                ('funcionarios', models.ManyToManyField(related_name='funcionarios', to=settings.AUTH_USER_MODEL)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maquinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Trator'), (2, 'Emplemento')], verbose_name='Tipo de Maquinário')),
                ('marca', models.CharField(max_length=200, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=200, verbose_name='Modelo')),
                ('ano_fabricacao', models.CharField(max_length=240, verbose_name='Ano')),
                ('horas_trabalhadas', models.PositiveIntegerField(verbose_name='Horas Trabalhadas')),
                ('data_aquisicao', models.DateField(auto_now_add=True, verbose_name='Data de Aquisição')),
                ('observacoes', models.TextField(verbose_name='Observações')),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário Registrado')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.fazenda')),
            ],
        ),
        migrations.CreateModel(
            name='Variedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=240, verbose_name='Nome')),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário Registrado')),
            ],
        ),
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('ano_plantio', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ano do plantio')),
                ('numero_covas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero de covas')),
                ('espacamento_rua', models.FloatField(blank=True, null=True, verbose_name='Espaçamento das ruas')),
                ('espacamento_cova', models.FloatField(blank=True, null=True, verbose_name='Espaçamento das covas')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='Área em hectare')),
                ('numero_covas_hectare', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de covas por hectare')),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário Registrado')),
                ('variedade', models.ManyToManyField(to='manager.Variedade')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Plantio'), (2, 'Fertilização'), (3, 'Preparação do Solo'), (4, 'Outros')], verbose_name='Tipo de Serviço')),
                ('data_inicio', models.DateField(verbose_name='Data de Inicio')),
                ('data_termino', models.DateField(verbose_name='Data de Término')),
                ('observacoes', models.TextField(verbose_name='Observações')),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário Registrado')),
                ('maquinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.maquinario')),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.talhao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
