# Generated by Django 3.2.7 on 2021-10-13 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fazenda',
            name='agronomos',
            field=models.ManyToManyField(blank=True, related_name='id_agronomos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fazenda',
            name='funcionarios',
            field=models.ManyToManyField(blank=True, related_name='id_funcionarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fazenda',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_proprietario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maquinario',
            name='fazenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_fazenda', to='manager.fazenda'),
        ),
        migrations.AlterField(
            model_name='talhao',
            name='variedade',
            field=models.ManyToManyField(related_name='id_variedade', to='manager.Variedade'),
        ),
    ]
