# Generated by Django 3.2.7 on 2021-11-10 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestacaoservico',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='prestacaoservico',
            name='funcionario',
            field=models.ManyToManyField(related_name='id_funcionario_ServicoMaquinario', to=settings.AUTH_USER_MODEL),
        ),
    ]
