# Generated by Django 3.2.7 on 2021-11-01 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fazenda',
            name='agronomos',
        ),
        migrations.RemoveField(
            model_name='fazenda',
            name='funcionarios',
        ),
        migrations.AlterField(
            model_name='fazenda',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_proprietario_Fazenda', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maquinario',
            name='fazenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_fazenda_Maquinario', to='manager.fazenda'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='maquinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_maquinario_Servico', to='manager.maquinario'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='talhao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_talhao_Servico', to='manager.talhao'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_Servico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='talhao',
            name='variedade',
            field=models.ManyToManyField(related_name='id_variedade_Talhao', to='manager.Variedade'),
        ),
        migrations.CreateModel(
            name='FuncionarioFazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('A', 'Agrônomo'), ('F', 'Funcionário')], max_length=1)),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário Registrado')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_fazenda_FuncionarioFazenda', to='manager.fazenda')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_funcionario_FuncionarioFazenda', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
