# Generated by Django 3.2.7 on 2021-11-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20211110_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestacaoservico',
            name='status',
            field=models.CharField(choices=[('A', 'Andamento'), ('C', 'Concluído')], default='A', max_length=2, verbose_name='Status'),
        ),
    ]
