# Generated by Django 3.2.7 on 2021-11-03 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_servicomaquinario_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='talhao',
            name='fazenda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_fazenda_Talhao', to='manager.fazenda'),
            preserve_default=False,
        ),
    ]
