# Generated by Django 3.2.7 on 2021-11-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_talhao_fazenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variedade',
            name='nome',
            field=models.CharField(max_length=240, unique=True, verbose_name='Nome'),
        ),
    ]
