# Generated by Django 3.2.7 on 2021-11-05 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_variedade_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='fazenda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_fazenda_Servico', to='manager.fazenda'),
            preserve_default=False,
        ),
    ]
