# Generated by Django 3.2.7 on 2021-11-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_servico_fazenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinario',
            name='data_aquisicao',
            field=models.DateField(verbose_name='Data de Aquisição'),
        ),
    ]
