# Generated by Django 3.2.7 on 2021-11-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_alter_maquinario_ano_fabricacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinario',
            name='ano_fabricacao',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano'),
        ),
    ]
