# Generated by Django 3.2.7 on 2021-11-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_maquinario_ano_fabricacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adubo',
            options={'verbose_name': 'Adubo', 'verbose_name_plural': 'Adubos'},
        ),
        migrations.AlterModelOptions(
            name='anotacaoconsultoria',
            options={'verbose_name': 'Anotação da Consultoria', 'verbose_name_plural': 'Anotações da Consultoria'},
        ),
        migrations.AlterModelOptions(
            name='colheita',
            options={'verbose_name': 'Colheita', 'verbose_name_plural': 'Colheitas'},
        ),
        migrations.AlterModelOptions(
            name='consultoriaagronomo',
            options={'verbose_name': 'Consultoria do Agrônomo', 'verbose_name_plural': 'Consultorias do Agrônomo'},
        ),
        migrations.AlterModelOptions(
            name='fazenda',
            options={'verbose_name': 'Fazenda', 'verbose_name_plural': 'Fazendas'},
        ),
        migrations.AlterModelOptions(
            name='fertilizacao',
            options={'verbose_name': 'Fertilização', 'verbose_name_plural': 'Fertilizaçôes'},
        ),
        migrations.AlterModelOptions(
            name='funcionariofazenda',
            options={'verbose_name': 'Funcionario da Fazenda', 'verbose_name_plural': 'Funcionarios da Fazenda'},
        ),
        migrations.AlterModelOptions(
            name='maquinario',
            options={'verbose_name': 'Maquinário', 'verbose_name_plural': 'Maquinários'},
        ),
        migrations.AlterModelOptions(
            name='pessoacontratada',
            options={'verbose_name': 'Pessoa Contratada', 'verbose_name_plural': 'Pessoas Contratadas'},
        ),
        migrations.AlterModelOptions(
            name='plantio',
            options={'verbose_name': 'Plantio', 'verbose_name_plural': 'Plantios'},
        ),
        migrations.AlterModelOptions(
            name='quantidadeplantio',
            options={'verbose_name': 'Quantidade do Plantio', 'verbose_name_plural': 'Quantidade dos Plantios'},
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterModelOptions(
            name='servicomaquinario',
            options={'verbose_name': 'Serviço do Maquinário', 'verbose_name_plural': 'Serviços do Maquinário'},
        ),
        migrations.AlterModelOptions(
            name='talhao',
            options={'verbose_name': 'Talhao', 'verbose_name_plural': 'Talhôes'},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.AlterModelOptions(
            name='turmacolheita',
            options={'verbose_name': 'Turma da Colheita', 'verbose_name_plural': 'Turmas da Colheita'},
        ),
        migrations.AlterModelOptions(
            name='variedade',
            options={'verbose_name': 'Variedade', 'verbose_name_plural': 'Variedades'},
        ),
    ]
