# Generated by Django 3.2.7 on 2021-11-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20211105_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquinario',
            name='data_aquisicao',
        ),
    ]
