# Generated by Django 3.2.7 on 2021-11-09 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_remove_maquinario_data_aquisicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultoriaagronomo',
            name='anotacao_consultoria',
        ),
    ]
