# Generated by Django 3.2.7 on 2021-11-10 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_remove_consultoriaagronomo_anotacao_consultoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacaoconsultoria',
            name='consultoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_consultoria_AnotacaoConsultoria', to='manager.consultoriaagronomo'),
            preserve_default=False,
        ),
    ]
