# Generated by Django 3.2.7 on 2021-11-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_anotacaoconsultoria_consultoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacaoconsultoria',
            name='titulo',
            field=models.CharField(default=1, max_length=100, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
