# Generated by Django 3.2.7 on 2021-11-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_agronomo',
            field=models.BooleanField(default=False, verbose_name='Usuário agronomo'),
        ),
    ]
