# Generated by Django 3.2.7 on 2021-09-28 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Trator'), (2, 'Emplemento')], verbose_name='Tipo de Maquinário')),
                ('marca', models.CharField(max_length=200, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=200, verbose_name='Modelo')),
                ('ano_fabricacao', models.CharField(max_length=240, verbose_name='Ano')),
                ('horas_trabalhadas', models.PositiveIntegerField(verbose_name='Horas Trabalhadas')),
                ('data_aquisicao', models.DateField(auto_now_add=True, verbose_name='Data de Aquisição')),
                ('observacoes', models.TextField(verbose_name='Observações')),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário Registrado')),
            ],
        ),
        migrations.CreateModel(
            name='Variedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=240, verbose_name='Nome')),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário Registrado')),
            ],
        ),
        migrations.RenameField(
            model_name='fazenda',
            old_name='data_hora_registrada',
            new_name='data_hora_registrado',
        ),
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('ano_plantio', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ano do plantio')),
                ('numero_covas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero de covas')),
                ('espacamento_rua', models.FloatField(blank=True, null=True, verbose_name='Espaçamento das ruas')),
                ('espacamento_cova', models.FloatField(blank=True, null=True, verbose_name='Espaçamento das covas')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='Área em hectare')),
                ('numero_covas_hectare', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de covas por hectare')),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário Registrado')),
                ('variedade', models.ManyToManyField(to='manager.Variedade')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Plantio'), (2, 'Fertilização'), (3, 'Preparação do Solo'), (4, 'Outros')], verbose_name='Tipo de Serviço')),
                ('data_inicio', models.DateField(verbose_name='Data de Inicio')),
                ('data_termino', models.DateField(verbose_name='Data de Término')),
                ('observacoes', models.TextField(verbose_name='Observações')),
                ('data_hora_registrado', models.DateTimeField(auto_now_add=True, verbose_name='Horário Registrado')),
                ('maquinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.maquinario')),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.talhao')),
            ],
        ),
        migrations.AddField(
            model_name='maquinario',
            name='fazenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.fazenda'),
        ),
    ]
